#!/bin/sh
# hermes-hint.sh — Python pain fixes for r/learnpython top issues (2026-06-23)
# Usage: ./hermes-hint.sh [glob|matplotlib|pygame|all]
# Safe for beginners • POSIX-compliant • Idempotent
# Generated by Hermes Agent — https://reddit.com/r/learnpython
set -e

echo "==> Hermes Python Hint — Top r/learnpython pain fixes"
echo "    $(date '+%Y-%m-%d') | Source: reddit.com/r/learnpython"
echo ""

MODE="${1:-all}"

# ── Helper ──────────────────────────────────────────────
check_python() {
    if command -v python3 >/dev/null 2>&1; then
        PYTHON="python3"
    elif command -v python >/dev/null 2>&1; then
        PYTHON="python"
    else
        echo "✗ Python not found. Install from https://python.org"
        exit 1
    fi
    echo "→ Python: $($PYTHON --version 2>&1)"
}

# ════════════════════════════════════════════════════════
# FIX 1: Recursive glob / pathlib for subdirectories
# Pain: glob.glob('path/*/:*Zone.Identifier') doesn't traverse subdirs
# https://reddit.com/r/learnpython/comments/1kq8xs6/
# ════════════════════════════════════════════════════════
fix_glob() {
    echo ""
    echo "── Fix 1: Recursive file search across subdirectories ──"
    echo "   Problem: glob.glob() with wildcards skips nested folders"
    echo "   Solution: Use pathlib.Path.rglob() or glob(recursive=True)"
    echo ""

    # Show the Python fix inline
    $PYTHON -c '
import textwrap
print(textwrap.dedent("""\
    # ▼ CORRECT WAY — use pathlib (Python 3.4+):
    from pathlib import Path

    # Find ALL Zone.Identifier files recursively
    for f in Path("/home/usr").rglob("*Zone.Identifier"):
        print(f"Found: {f}")
        # f.unlink()  # uncomment to delete

    # ▼ OR with glob module:
    import glob
    files = glob.glob("/home/usr/**/*Zone.Identifier", recursive=True)
    for f in files:
        print(f"Found: {f}")
        # import os; os.remove(f)  # uncomment to delete

    # ▼ SAFEST: dry-run first, then delete
    # Always print before you delete!
"""))
'
    echo "   Key: Use ** with recursive=True, or switch to pathlib.rglob()"
}

# ════════════════════════════════════════════════════════
# FIX 2: Matplotlib broken after system update (backend)
# Pain: ValueError: Key backend 'module://matplotlib_inline.backend_inline' not valid
# https://reddit.com/r/learnpython/comments/1kq9uch/
# ════════════════════════════════════════════════════════
fix_matplotlib() {
    echo ""
    echo "── Fix 2: Matplotlib broken after system update ──"
    echo "   Problem: 'matplotlib_inline' backend missing after macOS/brew update"
    echo "   Solution: Reinstall matplotlib + matplotlib-inline, or switch backend"
    echo ""

    if [ "$(uname)" = "Darwin" ]; then
        echo "   → Detected macOS. If you use Homebrew Python:"
        echo "     $PYTHON -m pip install --upgrade --force-reinstall matplotlib matplotlib-inline"
        echo ""
        echo "   → Or switch to a built-in backend (fastest fix):"
    else
        echo "   → Fix:"
        echo "     $PYTHON -m pip install --upgrade --force-reinstall matplotlib matplotlib-inline"
        echo ""
    fi

    $PYTHON -c '
print("""\
    # ▼ QUICK FIX — switch backend in your script:
    import matplotlib
    matplotlib.use("TkAgg")  # or "Qt5Agg", "macosx", "Agg"
    import matplotlib.pyplot as plt

    # ▼ PERMANENT FIX — set in matplotlibrc:
    # echo "backend: TkAgg" >> ~/.matplotlib/matplotlibrc

    # ▼ For Jupyter/VSCode specifically:
    # pip install matplotlib-inline ipympl
""")
'
    echo "   → Verify: $PYTHON -c 'import matplotlib; print(matplotlib.get_backend())'"
}

# ════════════════════════════════════════════════════════
# FIX 3: Module installed but not found (pip vs IDLE/editor)
# Pain: pygame works in Command Prompt but not in IDLE
# https://reddit.com/r/learnpython/comments/1kprxpg/
# ════════════════════════════════════════════════════════
fix_pygame() {
    echo ""
    echo "── Fix 3: Module installed but IDLE/editor can't find it ──"
    echo "   Problem: pip installed the module for a different Python"
    echo "   Solution: Use the SAME Python for pip and your editor"
    echo ""

    echo "   → Check which Python pip is using:"
    $PYTHON -c '
import sys, shutil
print(f"   Interpreter: {sys.executable}")
pip_path = shutil.which("pip") or shutil.which("pip3") or "not found"
print(f"   pip path:    {pip_path}")
print(f"   Packages go to: {sys.path[3] if len(sys.path) > 3 else sys.prefix}")
'
    echo ""
    echo "   → FIX: Always use 'python -m pip' (not bare 'pip'):"
    echo "     $PYTHON -m pip install pygame          # install"
    echo "     $PYTHON -m pip list | grep pygame      # verify"
    echo ""
    echo "   → For IDLE specifically: restart IDLE after pip install."
    echo "   → Switch to VSCode/PyCharm for fewer path issues."
}

# ── Main ────────────────────────────────────────────────
check_python

case "$MODE" in
    glob)       fix_glob ;;
    matplotlib) fix_matplotlib ;;
    pygame)     fix_pygame ;;
    all|*)      fix_glob; fix_matplotlib; fix_pygame ;;
esac

echo ""
echo "✓ Done. All fixes are read-only (no file changes made)."
echo "  More help: reddit.com/r/learnpython | docs.python.org"
