#!/usr/bin/env bash
# =============================================================================
# Hermes Pain-Point Terminal Hints - Generated 2026-06-11
# Source: r/learnpython scan via Pullpush API
# NOTE: Data is ~388-390 days old (Pullpush cache delay)
# =============================================================================
# Install: source this file in your ~/.bashrc or ~/.zshrc
# Then these preexec hooks will suggest fixes when you hit matching errors.

# --- Utility: clipboard (cross-platform) ---
_hclip() {
  if command -v pbcopy &>/dev/null; then echo "$1" | pbcopy
  elif command -v xclip &>/dev/null; then echo "$1" | xclip -selection clipboard
  elif command -v wl-copy &>/dev/null; then echo "$1" | wl-copy
  fi
}

# --- Hint 1: Matplotlib backend broken after system update ---
# Category: API | Trigger: ValueError "not a valid value for backend"
# https://reddit.com/r/learnpython/comments/1kq9uch/
_hermes_hint_matplotlib_backend() {
  if [[ "$1" == *"matplotlib_inline"* ]] || [[ "$1" == *"not a valid value for backend"* ]]; then
    echo ""
    echo "💡 Matplotlib Backend Fix: Your matplotlib-inline package is out of sync."
    echo "   We've copied the fix to your clipboard. Press Cmd+V (or Ctrl+Shift+V) and Enter."
    CMD="pip install --upgrade matplotlib-inline matplotlib"
    _hclip "$CMD"
    echo "   Command: pip install --upgrade matplotlib-inline matplotlib"
    echo ""
  fi
}
preexec_functions+=(_hermes_hint_matplotlib_backend)

# --- Hint 2: Python import path / PYTHONPATH issues ---
# Category: Environment | Trigger: ModuleNotFoundError
# https://reddit.com/r/learnpython/comments/1kokjeg/
_hermes_hint_pythonpath() {
  if [[ "$1" == *"ModuleNotFoundError"* ]] || [[ "$1" == *"No module named"* ]]; then
    echo ""
    echo "💡 Import Path Fix: Python can't find your module."
    echo "   Try adding your project root to PYTHONPATH:"
    CMD="export PYTHONPATH=\"\${PYTHONPATH}:\$(pwd)\""
    echo "   $CMD"
    echo "   Or structure as a package with __init__.py and use: pip install -e ."
    echo ""
  fi
}
preexec_functions+=(_hermes_hint_pythonpath)

# --- Hint 3: glob() not recursing into subdirectories ---
# Category: API | Trigger: glob usage without recursive
# https://reddit.com/r/learnpython/comments/1kq8xs6/
_hermes_hint_glob_recursive() {
  if [[ "$1" == *"glob"* ]]; then
    echo ""
    echo "💡 Glob Recursive Fix: Use recursive=True with ** pattern."
    echo "   import glob"
    echo "   files = glob.glob('/path/**/*.txt', recursive=True)"
    echo "   Docs: https://docs.python.org/3/library/glob.html"
    echo ""
  fi
}
preexec_functions+=(_hermes_hint_glob_recursive)

# --- Hint 4: Camera/package not found on ARM SBC (Orange Pi) ---
# Category: API | Trigger: "Unable to locate package" for camera libs
# https://reddit.com/r/learnpython/comments/1kq9gn9/
_hermes_hint_camera_lib() {
  if [[ "$1" == *"Unable to locate package"* ]] && [[ "$1" == *"camera"* ]]; then
    echo ""
    echo "💡 Camera Library Fix: Package may not be in apt repos on ARM SBCs."
    echo "   Try pip instead:"
    CMD="pip install opencv-python picamera2"
    _hclip "$CMD"
    echo "   $CMD"
    echo "   For Raspberry Pi/Orange Pi cameras: sudo apt install python3-libcamera"
    echo ""
  fi
}
preexec_functions+=(_hermes_hint_camera_lib)

# --- Hint 5: Python uninstall errors (Windows/macOS) ---
# Category: Environment | Trigger: Uninstall/repair errors
# https://reddit.com/r/learnpython/comments/1kon6uf/
_hermes_hint_python_uninstall() {
  if [[ "$1" == *"uninstall"* ]] || [[ "$1" == *"fatal error"* ]] && [[ "$1" == *"python"* ]]; then
    echo ""
    echo "💡 Python Uninstall Fix: Uninstalling system Python can break your OS."
    echo "   macOS: Use Homebrew - brew reinstall python@3.12"
    echo "   Linux: sudo apt install --reinstall python3"
    echo "   Windows: Use 'Add or Remove Programs' or the official Python installer 'Repair' option"
    echo ""
  fi
}
preexec_functions+=(_hermes_hint_python_uninstall)

# =============================================================================
# Generated by Hermes Agent — Pain-to-Pip pipeline
# Run: source hermes_pain_hints.sh
# =============================================================================
