#!/bin/sh
# hermes-hint.sh — Fix "install: illegal option -- r" when using pip on macOS
# Usage: ./hermes-hint-pip-requirements-fix.sh [requirements-file]
# Safe for beginners • POSIX-compliant • Idempotent
# Generated by Hermes Agent — 2026-07-18
# Source: r/learnpython pain scan — pip alias conflict on macOS

set -e

REQ_FILE="${1:-requirements.txt}"

echo "==> Hermes Hint — Fix pip 'install: illegal option -- r' on macOS"
echo ""

# Platform detection
if [ "$(uname)" = "Darwin" ]; then
    echo "→ Detected macOS. Using python3 -m pip (bypasses shell alias conflicts)..."
    echo ""
    
    # Check if requirements file exists
    if [ ! -f "$REQ_FILE" ]; then
        echo "⚠  '$REQ_FILE' not found in current directory."
        echo "   Usage: ./hermes-hint-pip-requirements-fix.sh [path/to/requirements.txt]"
        exit 1
    fi
    
    # Use python3 -m pip to bypass the 'install' alias conflict
    # The alias conflict happens when Homebrew coreutils shadows the pip command
    command -p python3 -m pip install -r "$REQ_FILE"
    
else
    echo "→ Detected Linux/other. Using standard pip..."
    echo ""
    
    if [ ! -f "$REQ_FILE" ]; then
        echo "⚠  '$REQ_FILE' not found in current directory."
        echo "   Usage: ./hermes-hint-pip-requirements-fix.sh [path/to/requirements.txt]"
        exit 1
    fi
    
    command -p python3 -m pip install -r "$REQ_FILE"
fi

echo ""
echo "✓ Done! Packages installed successfully."
echo ""
echo "💡 Why this happens: If 'pip' is aliased or shadowed by another command"
echo "   (common with Homebrew coreutils on macOS), the shell runs the wrong"
echo "   program. Using 'python3 -m pip' always calls the correct pip."
echo ""
echo "🔧 To permanently fix: Add this to your ~/.zshrc or ~/.bashrc:"
echo "   alias pip='python3 -m pip'"
