#!/bin/sh
# hermes-hint.sh — Fix pip SSL errors (CERTIFICATE_VERIFY_FAILED) + Python env health check
# Usage: ./hermes-hint.sh            # run health checks
#        ./hermes-hint.sh --fix-ssl  # upgrade certifi to fix SSL errors
# Safe for beginners • POSIX-compliant • Idempotent • No sudo
# Generated by Hermes (r/learnpython pain pipeline) — 20260916

echo "==> Python environment doctor — fixes pip SSL errors & diagnoses env issues"

# --- Platform detection ---
if [ "$(uname)" = "Darwin" ]; then
    OS="macOS"
else
    OS="$(uname)"
fi
echo "-> Detected OS: $OS"

# --- Python discovery ---
PY=python3
if ! command -v "$PY" >/dev/null 2>&1; then
    PY=python
fi
if ! command -v "$PY" >/dev/null 2>&1; then
    echo "! Python not found. Install it from https://python.org first."
    exit 1
fi
echo "-> Python: $($PY --version 2>&1)"
echo "-> Python path: $(command -v "$PY")"

# --- Health check: SSL / certificate ---
echo
echo "==> SSL certificate health check"
"$PY" -c "import ssl; print('  OK ssl module:', ssl.OPENSSL_VERSION)" 2>/dev/null \
    || echo "  ! ssl import failed — cert verification may be broken"

# --- Fix SSL (CERTIFICATE_VERIFY_FAILED) ---
if [ "${1:-}" = "--fix-ssl" ]; then
    echo
    echo "==> Upgrading certifi to fix CERTIFICATE_VERIFY_FAILED..."
    if "$PY" -m pip install --upgrade certifi 2>/dev/null; then
        echo "  OK certifi upgraded. Retry your pip install."
    else
        echo "  ! Upgrade failed. Fallback:"
        echo "    $PY -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org <package>"
    fi
fi

# --- Health check: pip <-> python alignment ---
echo
echo "==> pip <-> python alignment check"
if command -v pip3 >/dev/null 2>&1; then
    echo "-> pip3: $(command -v pip3)"
    echo "-> Tip: always use '$PY -m pip install <pkg>' to target the right Python"
else
    echo "-> pip3 not on PATH — use '$PY -m pip' instead"
fi

# --- Quick-reference summary ---
echo
echo "==> Quick fixes"
echo "  SSL error        -> $PY -m pip install --upgrade certifi"
echo "  Wrong Python     -> use '$PY -m pip' instead of bare 'pip'"
echo "  Module not found -> $PY -m pip install --user <pkg>, then verify: $PY -c 'import <pkg>'"
echo "  venv confusion   -> source venv/bin/activate, then $PY -m pip install <pkg>"
echo "  cwd/file error   -> run from script dir, or use pathlib with __file__"

echo
echo "OK Done. Re-run anytime — it is safe and idempotent."
