#!/usr/bin/env bash
# =============================================================================
# Hermes Terminal Hints — r/learnpython Pain Points (2026-05-23)
# Generated by Hermes Agent pain-scan pipeline
# Repo: github.com/minirr890112-byte/HermesMade
# 
# Drop-in: source this file in ~/.zshrc or ~/.bashrc
# Detects common Python errors in stderr and offers instant fixes.
# =============================================================================

# ── Shell detection ──
if [[ -n "$ZSH_VERSION" ]]; then
  HERMES_SHELL="zsh"
elif [[ -n "$BASH_VERSION" ]]; then
  HERMES_SHELL="bash"
else
  HERMES_SHELL="unknown"
fi

# ── Clipboard helper (cross-platform) ──
_hermes_clipboard() {
  if command -v pbcopy &>/dev/null; then
    echo "$1" | pbcopy
  elif command -v xclip &>/dev/null; then
    echo "$1" | xclip -selection clipboard
  elif command -v clip.exe &>/dev/null; then
    echo "$1" | clip.exe
  fi
}

# ═══════════════════════════════════════════════════════════════════════════
# HINT 1: pip install / SSL / certificate errors
# Pain: "CERTIFICATE_VERIFY_FAILED", "Could not find platform independent libraries"
# Category: Environment | Delivery: terminal-hint:auto-paste-hint
# ═══════════════════════════════════════════════════════════════════════════
_hermes_fix_pip_ssl() {
  local err="$1"
  if [[ "$err" == *"CERTIFICATE_VERIFY_FAILED"* ]] || [[ "$err" == *"SSL"* ]]; then
    printf "\n💡 [1;33mFix tip:[0m pip SSL certificate error detected.\n"
    printf "   We've copied the fix to your clipboard. Paste and run:\n"
    printf "   → [1;32mpip install --upgrade certifi\033[0m\n"
    _hermes_clipboard "pip install --upgrade certifi"
  elif [[ "$err" == *"Could not find platform independent libraries"* ]]; then
    printf "\n💡 [1;33mFix tip:[0m Python environment may be broken. Try:\n"
    printf "   → [1;32mpython3 -m venv .venv --clear && source .venv/bin/activate && pip install --upgrade pip setuptools wheel\033[0m\n"
    _hermes_clipboard "python3 -m venv .venv --clear && source .venv/bin/activate && pip install --upgrade pip setuptools wheel"
  elif [[ "$err" == *"No module named"* ]] || [[ "$err" == *"ModuleNotFoundError"* ]]; then
    local mod
    mod=$(echo "$err" | grep -oP "No module named '\K[^']+" | head -1)
    if [[ -n "$mod" ]]; then
      printf "\n💡 [1;33mMissing module:[0m %s\n" "$mod"
      printf "   → [1;32mpip install %s\033[0m\n" "$mod"
      _hermes_clipboard "pip install $mod"
    fi
  fi
}

# ═══════════════════════════════════════════════════════════════════════════
# HINT 2: venv/virtualenv issues
# Pain: "packages not getting detected by IDE", "venv directory problems"
# Category: Environment | Delivery: terminal-hint:auto-paste-hint
# ═══════════════════════════════════════════════════════════════════════════
_hermes_fix_venv() {
  local cmd="$1"
  if [[ "$cmd" == *"python"* ]] && [[ ! -n "$VIRTUAL_ENV" ]]; then
    if [[ -d ".venv" ]]; then
      printf "\n💡 [1;33mTip:[0m A .venv directory exists but isn't activated.\n"
      printf "   → [1;32msource .venv/bin/activate\033[0m\n"
      _hermes_clipboard "source .venv/bin/activate"
    fi
  fi
}

# ═══════════════════════════════════════════════════════════════════════════
# HINT 3: Python PATH / "command not found" / not recognized
# Pain: "python not recognized", "which python returns wrong path"
# Category: Environment | Delivery: terminal-hint:auto-paste-hint
# ═══════════════════════════════════════════════════════════════════════════
_hermes_fix_path() {
  local err="$1"
  if [[ "$err" == *"command not found"* ]] && [[ "$err" == *"python"* ]]; then
    printf "\n💡 [1;33mFix tip:[0m Python not found in PATH.\n"
    if [[ "$HERMES_SHELL" == "zsh" ]]; then
      printf "   → [1;32mecho 'export PATH="/usr/local/bin:\$PATH"' >> ~/.zshrc && source ~/.zshrc\033[0m\n"
    else
      printf "   → [1;32mecho 'export PATH="/usr/local/bin:\$PATH"' >> ~/.bashrc && source ~/.bashrc\033[0m\n"
    fi
  fi
}

# ═══════════════════════════════════════════════════════════════════════════
# HINT 4: Type errors / mypy / attribute errors
# Pain: "mypy error", "typeerror", "has no attribute"
# Category: API/Tooling | Delivery: terminal-hint:auto-paste-hint
# ═══════════════════════════════════════════════════════════════════════════
_hermes_fix_type_errors() {
  local err="$1"
  if [[ "$err" == *"has no attribute"* ]]; then
    local obj
    obj=$(echo "$err" | grep -oP "'[^']+' object has no attribute '\K[^']+" | head -1)
    printf "\n💡 [1;33mDebug tip:[0m Attribute error detected.\n"
    printf "   → [1;32mpython -c 'import <module>; print(dir(<module>))'\033[0m\n"
    printf "   → Or run: [1;32mpython -W all your_script.py\033[0m to see all warnings\n"
  elif [[ "$err" == *"mypy"* ]] || [[ "$err" == *"type"* ]]; then
    printf "\n💡 [1;33mType hint:[0m Consider running mypy with strict mode:\n"
    printf "   → [1;32mmypy --strict your_file.py\033[0m\n"
  fi
}

# ═══════════════════════════════════════════════════════════════════════════
# HINT 5: Deprecation warnings / FutureWarning
# Pain: "deprecated", "will be removed in future version"
# Category: API | Delivery: terminal-hint:auto-paste-hint
# ═══════════════════════════════════════════════════════════════════════════
_hermes_fix_deprecated() {
  local err="$1"
  if [[ "$err" == *"DeprecationWarning"* ]] || [[ "$err" == *"FutureWarning"* ]] || [[ "$err" == *"deprecated"* ]]; then
    printf "\n💡 [1;33mDeprecation alert:[0m Show all warnings with:\n"
    printf "   → [1;32mpython -W all your_script.py\033[0m\n"
    printf "   → Or filter: [1;32mpython -W default::DeprecationWarning your_script.py\033[0m\n"
  fi
}

# ═══════════════════════════════════════════════════════════════════════════
# HINT 6: IDE venv detection (VS Code / PyCharm)
# Pain: "IDE doesn't detect packages", "PyCharm can't find interpreter"
# Category: Tooling | Delivery: vscode-popup:one-click-button
# ═══════════════════════════════════════════════════════════════════════════
_hermes_fix_ide_venv() {
  if [[ -d ".venv" ]] && [[ -f ".venv/bin/python" ]]; then
    local py_path
    py_path="$(realpath .venv/bin/python 2>/dev/null || readlink -f .venv/bin/python 2>/dev/null || echo "$PWD/.venv/bin/python")"
    # Only show once per directory (track via temp file)
    local marker="/tmp/hermes_ide_hint_$(echo "$PWD" | md5sum 2>/dev/null | cut -c1-8 || echo "default")"
    if [[ ! -f "$marker" ]]; then
      printf "\n💡 [1;33mIDE tip:[0m This project has a venv at:\n"
      printf "   [1;32m%s\033[0m\n" "$py_path"
      printf "   VS Code: Cmd+Shift+P → 'Python: Select Interpreter' → Browse → paste path\n"
      printf "   PyCharm: Settings → Project → Python Interpreter → Add Local → paste path\n"
      touch "$marker"
    fi
  fi
}

# ═══════════════════════════════════════════════════════════════════════════
# HINT 7: Python version check / upgrade
# Pain: "version compatibility", "python 3.x vs 3.y"
# Category: Environment | Delivery: terminal-hint:auto-paste-hint
# ═══════════════════════════════════════════════════════════════════════════
_hermes_check_version() {
  if command -v python3 &>/dev/null; then
    local ver
    ver=$(python3 --version 2>&1 | grep -oP '\d+\.\d+')
    if [[ -n "$ver" ]]; then
      local major minor
      major=$(echo "$ver" | cut -d. -f1)
      minor=$(echo "$ver" | cut -d. -f2)
      if [[ "$major" -lt 3 ]] || [[ "$major" -eq 3 && "$minor" -lt 9 ]]; then
        printf "\n💡 [1;33mVersion:[0m Python %s is getting old. Consider upgrading:\n" "$ver"
        printf "   → [1;32mpyenv install 3.12 && pyenv global 3.12\033[0m\n"
      fi
    fi
  fi
}

# ═══════════════════════════════════════════════════════════════════════════
# HINT 8: Built-in docs quick access
# Pain: "no tutorials", "unclear docs", "how to use this module"
# Category: Docs | Delivery: web-overlay:default-value
# ═══════════════════════════════════════════════════════════════════════════
_hermes_quick_docs() {
  local cmd="$1"
  # If user typed "python" followed by a module name, offer docs
  if [[ "$cmd" =~ python.*\ -c\ .*import\ +([a-zA-Z0-9_]+) ]]; then
    local mod="${BASH_REMATCH[1]}"
    printf "\n💡 [1;33mDocs:[0m Quick help for \033[1;32m%s\033[0m:\n" "$mod"
    printf "   → [1;32mpython -c 'import %s; help(%s)'\033[0m\n" "$mod" "$mod"
  fi
}

# ═══════════════════════════════════════════════════════════════════════════
# HINT 9: pip upgrade reminder (periodic, non-annoying)
# Category: Environment | Delivery: terminal-hint:auto-paste-hint
# ═══════════════════════════════════════════════════════════════════════════
_hermes_pip_upgrade_reminder() {
  local marker="/tmp/hermes_pip_upgrade_check"
  local now
  now=$(date +%s)
  local last=0
  if [[ -f "$marker" ]]; then
    last=$(cat "$marker")
  fi
  # Check once every 7 days
  if (( now - last > 604800 )); then
    if command -v pip &>/dev/null; then
      local pip_ver
      pip_ver=$(pip --version 2>/dev/null | grep -oP '\d+\.\d+' | head -1)
      printf "\n💡 [1;33mMaintenance:[0m Keep pip up to date (checked weekly):\n"
      printf "   → [1;32mpip install --upgrade pip setuptools wheel\033[0m\n"
    fi
    echo "$now" > "$marker"
  fi
}

# ═══════════════════════════════════════════════════════════════════════════
# HOOK REGISTRATION — choose based on shell
# ═══════════════════════════════════════════════════════════════════════════

if [[ "$HERMES_SHELL" == "zsh" ]]; then
  # Zsh: preexec hook fires before every command
  _hermes_stderr_hook() {
    # Capture stderr from the last command
    exec 2>/tmp/hermes_last_stderr.$$
    local _hermes_last_err
    _hermes_last_err=$(cat /tmp/hermes_last_stderr.$$ 2>/dev/null)
    
    _hermes_fix_pip_ssl "$_hermes_last_err"
    _hermes_fix_path "$_hermes_last_err"
    _hermes_fix_type_errors "$_hermes_last_err"
    _hermes_fix_deprecated "$_hermes_last_err"
    
    rm -f /tmp/hermes_last_stderr.$$
  }
  
  # precmd hook: runs before each prompt (after command finishes)
  _hermes_precmd_hook() {
    _hermes_fix_venv "$(fc -ln -1 2>/dev/null)"
    _hermes_fix_ide_venv
    _hermes_quick_docs "$(fc -ln -1 2>/dev/null)"
    _hermes_check_version
    _hermes_pip_upgrade_reminder
  }
  
  autoload -Uz add-zsh-hook
  add-zsh-hook precmd _hermes_precmd_hook

elif [[ "$HERMES_SHELL" == "bash" ]]; then
  # Bash: PROMPT_COMMAND runs before each prompt
  _hermes_bash_hook() {
    local last_cmd
    last_cmd=$(history 1 2>/dev/null | sed 's/^[ ]*[0-9]*[ ]*//')
    _hermes_fix_venv "$last_cmd"
    _hermes_fix_ide_venv
    _hermes_quick_docs "$last_cmd"
    _hermes_check_version
    _hermes_pip_upgrade_reminder
  }
  
  # Append to existing PROMPT_COMMAND
  if [[ -z "$PROMPT_COMMAND" ]]; then
    PROMPT_COMMAND="_hermes_bash_hook"
  else
    PROMPT_COMMAND="$PROMPT_COMMAND;_hermes_bash_hook"
  fi
fi

# ── Cleanup helpers on source ──
if [[ "$HERMES_SHELL" == "zsh" ]]; then
  printf "\033[1;32m✅ Hermes terminal hints loaded\033[0m (zsh + precmd hook)\n"
  printf "   Detects: pip/SSL errors, venv issues, PATH problems, type errors, deprecation warnings\n"
elif [[ "$HERMES_SHELL" == "bash" ]]; then
  printf "\033[1;32m✅ Hermes terminal hints loaded\033[0m (bash + PROMPT_COMMAND)\n"
  printf "   Detects: pip/SSL errors, venv issues, PATH problems, type errors, deprecation warnings\n"
fi
