#!/usr/bin/env bash
# =============================================================================
# Hermes Terminal Hints — r/learnpython Pain Points (2026-05-01)
# Generated by Hermes Agent — pain-scan → classify → judge → hint pipeline
# Source: https://www.reddit.com/r/learnpython/
# =============================================================================
# Add this to your shell config:
#   bash: echo 'source ~/.hermes_hints.sh' >> ~/.bashrc
#   zsh:  echo 'source ~/.hermes_hints.sh' >> ~/.zshrc
# =============================================================================

# ---------------------------------------------------------------------------
# Hint 1: ModuleNotFoundError / pip install issues (Environment)
# Pain: "pip install pyqt qtwidgets" fails, venv confusion, wrong package names
# Reddit: https://reddit.com/r/learnpython/comments/1sxoimo/problem_with_pyqt5_widgets/
# ---------------------------------------------------------------------------
_fix_pip_install() {
    local stderr_output="$1"
    if [[ "$stderr_output" == *"ModuleNotFoundError"* ]]; then
        local module=$(echo "$stderr_output" | grep -oP "No module named '\K[^']+")
        if [[ -n "$module" ]]; then
            # Map common wrong names to correct pip packages
            case "$module" in
                PyQt5|pyqt5)   local pkg="PyQt5" ;;
                PyQt6|pyqt6)   local pkg="PyQt6" ;;
                cv2)           local pkg="opencv-python" ;;
                PIL)           local pkg="Pillow" ;;
                sklearn)       local pkg="scikit-learn" ;;
                *)             local pkg="$module" ;;
            esac
            printf "\n💡 Fix tip: Module '%s' not found.\n" "$module"
            if [[ -n "$VIRTUAL_ENV" ]]; then
                printf "   You're in a venv ✅ — run:\n"
                printf "   pip install %s\n" "$pkg"
                echo "pip install $pkg" | pbcopy 2>/dev/null || echo "pip install $pkg" | xclip -selection clipboard 2>/dev/null || true
            else
                printf "   ⚠️  No venv detected! Create one first:\n"
                printf "   python3 -m venv venv && source venv/bin/activate\n"
                printf "   pip install %s\n" "$pkg"
            fi
            printf "   (Command copied to clipboard)\n\n"
        fi
    fi
}

# ---------------------------------------------------------------------------
# Hint 2: Mutable default argument (API)
# Pain: "def f(lst=[]):" — list shared across all calls, silent wrong output
# Reddit: https://reddit.com/r/learnpython/comments/1szo06d/spent_two_days_on_a_bug_that_turned_out_to_be_a/
# ---------------------------------------------------------------------------
_fix_mutable_default() {
    local stderr_output="$1"
    # This is a pro-active hint shown when Python runs — we can't catch it from stderr
    # since it produces no error. Instead, we add a preexec hint.
    if [[ "$1" == *"python"* ]] || [[ "$1" == *".py"* ]]; then
        # Only show once per session
        if [[ -z "$_HERMES_MUTABLE_HINT_SHOWN" ]]; then
            export _HERMES_MUTABLE_HINT_SHOWN=1
            printf "\n🐍 Python PSA: Mutable default arguments are shared across ALL calls!\n"
            printf "   ❌ def f(items=[]):      # Same list every call!\n"
            printf "   ✅ def f(items=None):    # Safe pattern\n"
            printf "       if items is None: items = []\n"
            printf "   More: https://reddit.com/r/learnpython/comments/1szo06d/\n\n"
        fi
    fi
}

# ---------------------------------------------------------------------------
# Hint 3: Deployment — systemd for Python scripts (Environment)
# Pain: "3 days on dependency errors, broken environments and random crashes on VPS"
# Reddit: https://reddit.com/r/learnpython/comments/1sx19rh/built_my_first_real_python_script_with_ai_help/
# ---------------------------------------------------------------------------
_fix_python_deploy() {
    local stderr_output="$1"
    if [[ "$stderr_output" == *"Killed"* ]] || [[ "$stderr_output" == *"Terminated"* ]] ||        [[ "$stderr_output" == *"Connection refused"* ]] || [[ "$stderr_output" == *"command not found"* && "$1" == *"systemd"* ]]; then
        printf "\n🖥️  Deployment hint: Your Python process died. For 24/7 uptime, use systemd:\n"
        printf "   sudo tee /etc/systemd/system/myscript.service << 'EOF'\n"
        printf "   [Unit]\n"
        printf "   Description=My Python Service\n"
        printf "   After=network.target\n\n"
        printf "   [Service]\n"
        printf "   Type=simple\n"
        printf "   User=%s\n" "$USER"
        printf "   WorkingDirectory=%s\n" "$(pwd)"
        printf "   ExecStart=%s/venv/bin/python %s/script.py\n" "$(pwd)" "$(pwd)"
        printf "   Restart=always\n"
        printf "   RestartSec=10\n\n"
        printf "   [Install]\n"
        printf "   WantedBy=multi-user.target\n"
        printf "   EOF\n"
        printf "   sudo systemctl daemon-reload && sudo systemctl enable --now myscript\n"
        printf "   (systemd template copied to clipboard)\n\n"
        echo "sudo tee /etc/systemd/system/myscript.service << 'EOF'
[Unit]
Description=My Python Service
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$(pwd)
ExecStart=$(pwd)/venv/bin/python $(pwd)/script.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload && sudo systemctl enable --now myscript" | pbcopy 2>/dev/null || true
    fi
}

# ---------------------------------------------------------------------------
# Hint 4: UnboundLocalError — function ordering & scope (API)
# Pain: "UnboundLocalError: cannot access local variable 'SelectColor'"
# Reddit: https://reddit.com/r/learnpython/comments/1sx6dz4/can_someone_please_help_me/
# ---------------------------------------------------------------------------
_fix_unbound_local() {
    local stderr_output="$1"
    if [[ "$stderr_output" == *"UnboundLocalError"* ]]; then
        printf "\n🔧 Fix tip: UnboundLocalError means Python thinks your variable is local.\n"
        printf "   Common causes:\n"
        printf "   1. Nested function defined AFTER it's called — move def above the call.\n"
        printf "   2. Variable assigned inside function but read above the assignment.\n"
        printf "   3. Missing 'global' or 'nonlocal' declaration.\n"
        printf "   → Move all function definitions to the TOP of your script.\n"
        printf "   More: https://reddit.com/r/learnpython/comments/1sx6dz4/\n\n"
    fi
}

# ---------------------------------------------------------------------------
# Hint 5: Regex tokenizer inconsistency (API)
# Pain: Regex works on test string but breaks on file content
# Reddit: https://reddit.com/r/learnpython/comments/1szvtks/splitting_with_s/
# ---------------------------------------------------------------------------
_fix_regex_file() {
    local stderr_output="$1"
    if [[ "$stderr_output" == *"AttributeError"* && "$stderr_output" == *"tokenize"* ]]; then
        printf "\n📝 Regex hint: Inconsistent regex behavior between test string and file?\n"
        printf "   Common pitfall: file.read() includes invisible characters, different quotes,\n"
        printf "   or encoding issues. Debug with:\n"
        printf "   print(repr(file_content[:200]))  # See raw characters\n"
        printf "   print(file_content.encode('utf-8'))  # Check encoding\n"
        printf "   More: https://reddit.com/r/learnpython/comments/1szvtks/\n\n"
    fi
}

# =============================================================================
# Hook into shell error handling
# =============================================================================

# For zsh — captures stderr after each command
if [[ -n "$ZSH_VERSION" ]]; then
    _hermes_preexec() {
        _hermes_last_cmd="$1"
    }
    _hermes_precmd() {
        if [[ $? -ne 0 ]] && [[ -n "$_hermes_stderr_buffer" ]]; then
            _fix_pip_install "$_hermes_stderr_buffer"
            _fix_unbound_local "$_hermes_stderr_buffer"
            _fix_python_deploy "$_hermes_stderr_buffer"
            _fix_regex_file "$_hermes_stderr_buffer"
        fi
        _fix_mutable_default "$_hermes_last_cmd"
        _hermes_stderr_buffer=""
    }
    autoload -Uz add-zsh-hook
    add-zsh-hook preexec _hermes_preexec
    add-zsh-hook precmd _hermes_precmd
    # Capture stderr
    exec 2> >(while IFS= read -r line; do
        _hermes_stderr_buffer+="$line"$'\n'
        print -u2 -- "$line"
    done)
fi

# For bash — uses DEBUG trap
if [[ -n "$BASH_VERSION" ]] && [[ -z "$ZSH_VERSION" ]]; then
    _hermes_debug_trap() {
        _hermes_last_cmd="$BASH_COMMAND"
    }
    trap '_hermes_debug_trap' DEBUG
    
    _hermes_err_trap() {
        local last_stderr=$(cat /tmp/hermes_stderr_$$ 2>/dev/null)
        _fix_pip_install "$last_stderr"
        _fix_unbound_local "$last_stderr"
        _fix_python_deploy "$last_stderr"
        _fix_regex_file "$last_stderr"
        rm -f /tmp/hermes_stderr_$$
    }
    trap '_hermes_err_trap' ERR
    
    # Redirect stderr through a temp file for bash (simpler approach)
    exec 2> >(tee /tmp/hermes_stderr_$$ >&2)
    _fix_mutable_default ""
fi

echo "🐍 Hermes Python Hints loaded — protecting you from common r/learnpython pitfalls!"
