#!/bin/sh
# hermes-hint.sh — Fix "externally-managed-environment" pip error
# Usage: ./hermes-hint.sh [package-name]
# Safe for beginners • POSIX-compliant • Idempotent • Cross-platform
# Generated by Hermes Pain Pipeline • r/learnpython scan 2026-07-29
set -e

PACKAGE="${1:-}"
if [ -z "$PACKAGE" ]; then
  echo "==> Hermes Hint: externally-managed-environment fix"
  echo "    Your system Python is locked. Use a virtual environment instead."
  echo ""
  echo "Usage: ./hermes-hint.sh <package-name>"
  echo "Example: ./hermes-hint.sh requests"
  echo ""
  echo "What this fixes:"
  echo "  error: externally-managed-environment"
  echo "  This environment is externally managed"
  echo ""
  echo "Options (safest first):"
  echo "  1. ./hermes-hint.sh <pkg>     — Create venv + install package"
  echo "  2. pipx install <pkg>         — For CLI tools (needs pipx)"
  echo ""
  exit 0
fi

echo "==> Hermes Hint: Creating venv & installing '$PACKAGE'"
echo "    Fixes: externally-managed-environment pip error"
echo ""

# Detect platform
if [ "$(uname)" = "Darwin" ]; then
  echo "-> Detected macOS"
else
  echo "-> Detected Linux"
fi

# Check python3
if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 not found. Install: https://python.org/downloads/"
  exit 1
fi

PYTHON_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo "-> Found Python $PYTHON_VER"

# Step 1: Create .venv
VENV_DIR=".venv"
if [ ! -d "$VENV_DIR" ]; then
  echo "-> Creating virtual environment in $VENV_DIR ..."
  python3 -m venv "$VENV_DIR"
  echo "   Done."
else
  echo "-> Virtual environment already exists at $VENV_DIR (reusing)"
fi

# Step 2: Install package
echo "-> Installing '$PACKAGE' into venv ..."
. "$VENV_DIR/bin/activate"
pip install --quiet "$PACKAGE"
echo "   Done."

# Step 3: Verify
echo "-> Verifying installation ..."
python3 -c "import $PACKAGE; print(f'   $PACKAGE v{$PACKAGE.__version__ if hasattr($PACKAGE, "__version__") else "installed"} OK')" 2>/dev/null ||   python3 -c "import $PACKAGE; print(f'   $PACKAGE imported OK')" 2>/dev/null ||   echo "   (could not verify import — package may use a different import name)"

echo ""
echo "=========================================="
echo "  Ready! Activate your venv with:"
echo "    source $VENV_DIR/bin/activate"
echo ""
echo "  Or run directly:"
echo "    $VENV_DIR/bin/python your_script.py"
echo ""
echo "  To deactivate when done:"
echo "    deactivate"
echo "=========================================="
