#!/bin/sh
# hermes-hint.sh — Fix "TypeError: cannot use pandas.Series as a set element"
# Usage: ./hermes-hint-pandas-series-fix-20260731.sh
# Safe for beginners • POSIX-compliant • Idempotent
# Generated by Hermes Agent from r/learnpython pain scan (2026-07-31)
# Source: https://www.reddit.com/r/learnpython/comments/1vbfos9/
set -e

echo "==> Pandas Series / sklearn TypeError Fix"
echo "   Fixes: TypeError: cannot use 'pandas.Series' as a set element (unhashable type: 'Series')"
echo "   Cause: scikit-learn encoders receive pandas Series instead of numpy array"
echo ""

# Detect Python
if command -v python3 >/dev/null 2>&1; then
    PYTHON=python3
elif command -v python >/dev/null 2>&1; then
    PYTHON=python
else
    echo "[FAIL] Python not found. Install Python 3.8+ from https://python.org"
    exit 1
fi

# Check sklearn and pandas are installed
echo "→ Checking dependencies..."
$PYTHON -c "import sklearn, pandas" 2>/dev/null && echo "   sklearn + pandas: OK" || {
    echo "   [WARN] sklearn or pandas not found. Install with:"
    echo "     $PYTHON -m pip install scikit-learn pandas"
}

echo ""
echo "→ The Fix: Convert pandas Series to numpy array before passing to sklearn"
echo ""
echo "  BEFORE (broken):"
echo "    encoder.fit_transform(df['column'])         # passes Series → TypeError"
echo "    encoder.fit_transform(df[['col1','col2']])  # passes DataFrame → TypeError"
echo ""
echo "  AFTER (fixed):"
echo "    encoder.fit_transform(df['column'].values)          # .values → numpy array"
echo "    encoder.fit_transform(df[['col1','col2']].values)   # .values → numpy array"
echo ""
echo "  Alternatives (pandas >= 0.24):"
echo "    encoder.fit_transform(df['column'].to_numpy())"
echo "    encoder.fit_transform(df['column'].to_list())"
echo ""

# Quick verification if sklearn+pandas available
if $PYTHON -c "import sklearn, pandas" 2>/dev/null; then
    echo "→ Running quick verification..."
    $PYTHON -c "
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
try:
    # This would fail: le.fit_transform(pd.Series(['a','b','a']))
    result = le.fit_transform(pd.Series(['a','b','a']).values)
    print(f'   Verified: .values() works → {list(result)}')
except Exception as e:
    print(f'   [WARN] {e}')
" 2>/dev/null || echo "   (verification skipped — check your sklearn version)"
fi

echo ""
echo "✓ Done. Quick recap:"
echo "  Replace  df['col']  with  df['col'].values  before passing to sklearn."
echo ""
echo "  If you still see errors, try:"
echo "    $PYTHON -m pip install --upgrade scikit-learn"
echo "    $PYTHON -m pip install --upgrade pandas"
echo ""
echo "  Related docs: https://scikit-learn.org/stable/modules/preprocessing.html"
