#!/usr/bin/env bash
# Terminal Hint: Fix "pip install -r requirements.txt" errors on macOS
# Generated by Hermes Agent — Pain Scan Pipeline
# Source: r/learnpython pain point scan — June 13, 2026
# Reddit: https://reddit.com/r/learnpython/comments/1kphir9/
#
# Problem: New Python users on macOS type "pip install -r requirements.txt"
#          but get "install: illegal option -- r" because pip is not installed
#          or is aliased to another command (e.g., macOS built-in 'install')
#
# Solution: Use python3 -m pip instead of bare pip, or install pip first.

# Auto-fix: pip command not found or wrong pip
_fix_pip_install() {
    local last_cmd="$1"
    local last_exit="$2"
    local last_stderr="$3"

    # Detect: user tried "pip install" and it failed
    if [[ "$last_cmd" == *"pip install"* && "$last_exit" -ne 0 ]]; then
        # Check if stderr contains "illegal option" or "command not found"
        if [[ "$last_stderr" == *"illegal option"* ]] || [[ "$last_stderr" == *"command not found"* ]] || [[ "$last_stderr" == *"not found"* ]]; then
            echo ""
            echo "💡 Hermes Tip: It looks like 'pip' isn't set up on your system."
            echo "   Try this instead:"
            echo ""
            echo "   python3 -m pip install -r requirements.txt"
            echo ""
            echo "   Or install pip first:"
            echo "   python3 -m ensurepip --upgrade"
            echo ""

            # Auto-copy to clipboard (macOS)
            if command -v pbcopy &>/dev/null; then
                echo "python3 -m pip install -r requirements.txt" | pbcopy
                echo "   📋 Command copied to clipboard! Just press Cmd+V and Enter."
            elif command -v xclip &>/dev/null; then
                echo "python3 -m pip install -r requirements.txt" | xclip -selection c
                echo "   📋 Command copied to clipboard! Just press Ctrl+Shift+V and Enter."
            fi
            echo ""
        fi
    fi

    # Detect: ModuleNotFoundError
    if [[ "$last_stderr" == *"ModuleNotFoundError"* ]]; then
        local module=$(echo "$last_stderr" | grep -oP "No module named '\K[^']+")
        if [[ -n "$module" ]]; then
            echo ""
            echo "💡 Hermes Tip: Missing Python module '$module'."
            echo "   Install it with:"
            echo ""
            echo "   python3 -m pip install $module"
            echo ""
            if command -v pbcopy &>/dev/null; then
                echo "python3 -m pip install $module" | pbcopy
                echo "   📋 Command copied to clipboard! Press Cmd+V and Enter."
            fi
            echo ""
        fi
    fi
}

# ===== INSTALLATION =====
# Add this to your shell config:
#
#   For Zsh (~/.zshrc):
#     preexec_functions+=(_fix_pip_install)
#
#   For Bash (~/.bashrc):
#     trap '_fix_pip_install "$BASH_COMMAND" "$?" "$(cat /tmp/last_stderr 2>/dev/null)"' DEBUG
#     # Also capture stderr:
#     exec 2> >(tee /tmp/last_stderr >&2)
#
# Or simply run this script to install automatically:
install_hint() {
    local shell_rc
    if [[ "$SHELL" == *"zsh"* ]]; then
        shell_rc="$HOME/.zshrc"
        if ! grep -q "_fix_pip_install" "$shell_rc" 2>/dev/null; then
            echo "" >> "$shell_rc"
            echo "# Hermes: Auto-fix pip install errors" >> "$shell_rc"
            echo "preexec_functions+=(_fix_pip_install)" >> "$shell_rc"
            echo "✅ Installed to ~/.zshrc — restart your shell or run: source ~/.zshrc"
        else
            echo "✅ Already installed in ~/.zshrc"
        fi
    elif [[ "$SHELL" == *"bash"* ]]; then
        shell_rc="$HOME/.bashrc"
        if ! grep -q "_fix_pip_install" "$shell_rc" 2>/dev/null; then
            echo "" >> "$shell_rc"
            echo "# Hermes: Auto-fix pip install errors" >> "$shell_rc"
            echo 'trap '''_fix_pip_install "$BASH_COMMAND" "$?" "$(cat /tmp/last_stderr 2>/dev/null)"''' DEBUG' >> "$shell_rc"
            echo "exec 2> >(tee /tmp/last_stderr >&2)" >> "$shell_rc"
            echo "✅ Installed to ~/.bashrc — restart your shell or run: source ~/.bashrc"
        else
            echo "✅ Already installed in ~/.bashrc"
        fi
    else
        echo "⚠️  Unknown shell. Add _fix_pip_install to your shell's preexec function."
    fi
}

# Run installation if script executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    install_hint
fi
