#!/usr/bin/env bash
# ==============================================================================
# r/learnpython Pain Signal: pip install -r requirements.txt fails on macOS
# Post: "Need help with installing requirements.txt" (reddit.com/r/learnpython)
#   - macOS says 'install: illegal option -- r' when running pip install -r
#   - Root cause: `pip` resolves to Apple's /usr/bin/install, not Python's pip
# Generated by: Hermes Agent reddit-pain-workflow pipeline
# Pain ID: 1kphir9 | Priority Score: 82 | Category: Environment
# ==============================================================================

set -euo pipefail

VERBOSE=false
[[ "${1:-}" == "-v" || "${1:-}" == "--verbose" ]] && VERBOSE=true

log()  { $VERBOSE && echo "  [INFO]  $*" >&2 || true; }
warn() { echo "  [WARN]  $*" >&2; }
ok()   { echo "  [OK]    $*"; }

# ── Step 0: Detect the right Python command ──────────────────────────────────
PYTHON=""
for cmd in python3 python; do
    if command -v "$cmd" &>/dev/null; then
        ver=$("$cmd" --version 2>&1 || true)
        if [[ "$ver" == Python\ 3* ]]; then
            PYTHON="$cmd"
            break
        fi
    fi
done

if [[ -z "$PYTHON" ]]; then
    warn "No Python 3 found on this system."
    echo ""
    echo "  Install Python 3 first:"
    echo "    macOS:   brew install python3"
    echo "    Ubuntu:  sudo apt install python3 python3-pip"
    echo "    Arch:    sudo pacman -S python python-pip"
    exit 1
fi

log "Using Python: $PYTHON ($("$PYTHON" --version 2>&1))"

# ── Step 1: Check if pip module is available ─────────────────────────────────
if ! "$PYTHON" -m pip --version &>/dev/null; then
    warn "pip module not available for $PYTHON."
    echo ""
    echo "  Install pip:"
    echo "    macOS:   $PYTHON -m ensurepip --upgrade"
    echo "    Ubuntu:  sudo apt install ${PYTHON}-pip  (e.g., python3-pip)"
    echo "    Or:      curl -sS https://bootstrap.pypa.io/get-pip.py | $PYTHON"
    exit 2
fi

log "pip version: $($PYTHON -m pip --version)"

# ── Step 2: Find and validate requirements.txt ───────────────────────────────
REQ_FILE=""
if [[ -f "requirements.txt" ]]; then
    REQ_FILE="requirements.txt"
elif [[ -f "${1:-}" && "${1:-}" != "-v" && "${1:-}" != "--verbose" ]]; then
    REQ_FILE="${1}"
else
    # Search for it
    REQ_FILE=$(find . -maxdepth 2 -name "requirements.txt" -type f 2>/dev/null | head -1)
fi

if [[ -z "$REQ_FILE" ]]; then
    warn "No requirements.txt found."

    echo ""
    echo "  Usage:"
    echo "    $0 [path/to/requirements.txt]"
    echo ""
    echo "  Try:"
    echo "    cd /path/to/your/project/"
    echo "    $0 requirements.txt"
    exit 3
fi

if [[ ! -f "$REQ_FILE" ]]; then
    warn "File not found: $REQ_FILE"
    exit 3
fi

log "Requirements file: $REQ_FILE ($(wc -l < "$REQ_FILE" | tr -d ' ') lines)"

# ── Step 3: The Fix — use 'python -m pip' instead of bare 'pip' ──────────────
# WHY: macOS has /usr/bin/install (Apple's binary) which shadows pip.
#      Using 'python3 -m pip' bypasses shell command resolution entirely.
#      This works on ALL platforms: macOS, Linux, Windows (Git Bash, WSL).

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  💡 The Fix: NEVER use bare 'pip' on macOS                   ║"
echo "║                                                              ║"
echo "║  ❌ pip install -r requirements.txt  ← may hit /usr/bin/install"
echo "║  ✅ python3 -m pip install -r requirements.txt               ║"
echo "║                                                              ║"
echo "║  This runs pip as a Python module — safe on ALL platforms.   ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

log "Installing packages from $REQ_FILE ..."

# ── Step 4: Install (with platform-appropriate flags) ────────────────────────
PIP_CMD="$PYTHON -m pip install -r \"$REQ_FILE\""

# Check for virtual environment
if [[ -n "${VIRTUAL_ENV:-}" ]]; then
    log "Detected virtualenv: $VIRTUAL_ENV"
elif [[ -n "${CONDA_DEFAULT_ENV:-}" ]]; then
    log "Detected conda env: $CONDA_DEFAULT_ENV"
else
    warn "No virtual environment detected. Installing packages globally."
    warn "Consider: $PYTHON -m venv venv && source venv/bin/activate"
    echo ""
fi

# Actually install
if $PIP_CMD; then
    ok "All packages installed successfully from $REQ_FILE"
else
    warn "Some packages failed to install. Check the output above."
    echo ""
    echo "  Common fixes:"
    echo "    • SSL errors  → $PYTHON -m pip install --upgrade certifi"
    echo "    • Permission  → do NOT use sudo; use a virtualenv instead"
    echo "    • Missing lib → check brew/apt for system deps (e.g., openssl, python3-dev)"
    exit 4
fi

# ── Step 5: Verify installation ──────────────────────────────────────────────
log "Verifying installed packages ..."
$PYTHON -m pip check 2>&1 || warn "Some dependency conflicts detected (pip check failed)"

echo ""
ok "Done! All packages from '$REQ_FILE' are installed."
echo ""
echo "  Pro tip: Add this to your ~/.zshrc or ~/.bashrc:"
echo "    alias pip='python3 -m pip'"
echo "  This will prevent the 'illegal option' error forever."
