#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════╗
# ║  Hermes Terminal Hints — Auto-generated Pain Solutions          ║
# ║  Source: r/learnpython scan — 2026-04-26                        ║
# ║  Generated by: Hermes Agent (cron)                              ║
# ║  Target: 3 high-signal Environment & Tooling pain points         ║
# ╚══════════════════════════════════════════════════════════════════╝

# ─────────────────────────────────────────────────────────────────
# HINT 1: Fix pip install failures on new Python versions
# Pain: "[HELP] Unable to install pandas and other libs. Kubuntu 26.04"
# Symptom: "ERROR: Could not find a version that satisfies the requirement pandas"
# Root cause: Ubuntu 26.04 ships Python 3.14 — packages not yet built for it
# Category: Environment | Channel: terminal-hint (on-error)
# Source: https://reddit.com/r/learnpython/comments/1sueb9e/
# ─────────────────────────────────────────────────────────────────
_fix_pip_new_python() {
    local stderr_log="$1"

    if echo "$stderr_log" | grep -q "No matching distribution found"; then
        echo ""
        echo "💡  Hermes Hint: Python version too new for this package!"
        echo "    ─────────────────────────────────────────────────"

        if command -v apt-get &>/dev/null; then
            echo "    📋 Linux fix (copied to clipboard):"
            FIX_CMD="sudo add-apt-repository -y ppa:deadsnakes/ppa && sudo apt update && sudo apt install -y python3.13 python3.13-venv && python3.13 -m venv ~/hermes_py313 && source ~/hermes_py313/bin/activate && pip install --upgrade pip"
            echo "    $ $FIX_CMD"

            if command -v pbcopy &>/dev/null; then
                printf '%s' "$FIX_CMD" | pbcopy
            elif command -v xclip &>/dev/null; then
                printf '%s' "$FIX_CMD" | xclip -selection clipboard
            elif command -v wl-copy &>/dev/null; then
                printf '%s' "$FIX_CMD" | wl-copy
            fi
            echo "    Press Cmd+V / Ctrl+Shift+V and Enter to run."
        elif command -v brew &>/dev/null; then
            echo "    📋 macOS fix:"
            echo "    $ brew install python@3.13 && python3.13 -m venv ~/hermes_py313 && source ~/hermes_py313/bin/activate"
        fi
        echo "    ✅ Then retry: pip install <your-package>"
        echo ""
    fi
}

# ─────────────────────────────────────────────────────────────────
# HINT 2: Fix .py files not accepting drag-and-drop on Windows
# Pain: ".py files not accepting files to be dropped onto them"
# Symptom: After Python reinstall via web installer, drag-drop handler breaks
# Root cause: Python web installer corrupts shell association
# Category: Environment | Channel: terminal-hint (on-error)
# Source: https://reddit.com/r/learnpython/comments/1suv2fn/
# ─────────────────────────────────────────────────────────────────
_fix_py_drag_drop() {
    local stderr_log="$1"

    if echo "$stderr_log" | grep -qi "cannot execute\|permission denied\|no such file.*\.py"; then
        echo ""
        echo "💡  Hermes Hint: .py file handler issue detected!"
        echo "    ───────────────────────────────────────────"
        echo "    If you're on Windows:"
        echo "    → Reinstall Python using the Windows Store app (not the web installer)"
        echo '    → Or run: python "C:\path\to\script.py" "C:\path\to\file.txt"'
        echo "    If you're on macOS/Linux:"
        echo "    → Add shebang: echo '#!/usr/bin/env python3' > script.py"
        echo "    → Make executable: chmod +x script.py"
        echo "    → Run: ./script.py file_to_drop.txt"
        echo ""
    fi
}

# ─────────────────────────────────────────────────────────────────
# HINT 3: AttributeError: 'self' module has no attribute 'XYZ'
# Pain: "AttributeError: module 'self' has no attribute 'femboy_color'"
# Symptom: Using 'self.attribute' outside of a class method
# Root cause: Code runs 'self.attr = X' at module level (no __init__)
# Category: UX | Channel: terminal-hint (on-error)
# Source: https://reddit.com/r/learnpython/comments/1st3oev/
# ─────────────────────────────────────────────────────────────────
_fix_self_attribute_error() {
    local stderr_log="$1"

    if echo "$stderr_log" | grep -q "module 'self' has no attribute"; then
        echo ""
        echo "💡  Hermes Hint: 'self' used outside a class method!"
        echo "    ─────────────────────────────────────────────"
        echo "    This error means you're using 'self.attribute' in code that"
        echo "    isn't inside a class method (no 'def __init__(self):' wrapper)."
        echo ""
        echo "    📋 Fix pattern (copied to clipboard):"
        cat << 'HERMES_FIX'
class MyClass:
    def __init__(self):
        self.your_attribute = value  # define it here
    def your_method(self):
        print(self.your_attribute)   # now this works
HERMES_FIX

        FIX_PATTERN='class MyClass:\n    def __init__(self):\n        self.your_attribute = value\n    def your_method(self):\n        print(self.your_attribute)'
        if command -v pbcopy &>/dev/null; then
            printf '%s' "$FIX_PATTERN" | pbcopy
        elif command -v xclip &>/dev/null; then
            printf '%s' "$FIX_PATTERN" | xclip -selection clipboard
        elif command -v wl-copy &>/dev/null; then
            printf '%s' "$FIX_PATTERN" | wl-copy
        fi
        echo ""
        echo "    ✅ Paste this into your .py file and adapt it."
        echo ""
    fi
}

# ─────────────────────────────────────────────────────────────────
# SHELL INTEGRATION — zsh (preexec/precmd hooks)
# ─────────────────────────────────────────────────────────────────
if [[ -n "$ZSH_VERSION" ]]; then
    _hermes_capture_and_check() {
        # Save stderr, redirect to temp file
        exec 3>&2
        HERMES_STDERR_TMP=$(mktemp /tmp/hermes_stderr.XXXXXX)
        exec 2> >(tee "$HERMES_STDERR_TMP" >&3)
    }

    _hermes_check_and_hint() {
        # Restore stderr
        exec 2>&3 3>&-

        if [[ -f "$HERMES_STDERR_TMP" ]]; then
            local stderr_content
            stderr_content=$(cat "$HERMES_STDERR_TMP" 2>/dev/null)

            _fix_pip_new_python "$stderr_content"
            _fix_py_drag_drop "$stderr_content"
            _fix_self_attribute_error "$stderr_content"

            rm -f "$HERMES_STDERR_TMP"
        fi
    }

    autoload -Uz add-zsh-hook
    add-zsh-hook preexec _hermes_capture_and_check
    add-zsh-hook precmd _hermes_check_and_hint

    echo "🛡️  Hermes Terminal Hints loaded! (zsh — auto-triggers on errors)"
fi

# ─────────────────────────────────────────────────────────────────
# SHELL INTEGRATION — bash (ERR trap)
# ─────────────────────────────────────────────────────────────────
if [[ -n "$BASH_VERSION" ]]; then
    _hermes_bash_trap() {
        local exit_code=$?
        if [[ $exit_code -ne 0 ]]; then
            _fix_pip_new_python ""
            _fix_py_drag_drop ""
            _fix_self_attribute_error ""
        fi
        return $exit_code
    }
    trap _hermes_bash_trap ERR

    echo "🛡️  Hermes Terminal Hints loaded! (bash — auto-triggers on errors)"
fi

echo "   📊 Based on 60 pain signals from r/learnpython"
echo "   🔗 Report: https://reddit.com/r/learnpython"
echo "   📁 Add to shell: echo \"source $(realpath "$0" 2>/dev/null || echo "$PWD/$0")\" >> ~/.zshrc"
echo ""
